name: tests

on:
  push:
    branches: [ main ]
    paths:
      - grammar.js
      - src/**
      - test/**
  pull_request:
    paths:
      - grammar.js
      - src/**
      - test/**

jobs:
  test:
    name: Run tests
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup tree-sitter
        uses: tree-sitter/setup-action/cli@v1
      - name: Run tests
        uses: tree-sitter/parser-test-action@v2
